In [1]:
import numpy as np
import h5py
import scipy
from scipy import misc,optimize
import marshal
import copy

In [45]:
# Loading the data
with h5py.File('../HAR/preprocessed.hdf5','r') as hf:
    x_train = np.array(hf.get('x_train'))
    y_train = np.array(hf.get('y_train'))
    s_train = np.array(hf.get('s_train'))
    x_test = np.array(hf.get('x_test'))
    y_test = np.array(hf.get('y_test'))
    s_test = np.array(hf.get('s_test'))
    x_train_with_past = np.array(hf.get('x_train_with_past'))
    y_train_with_past = np.array(hf.get('y_train_with_past'))
    x_test_with_past = np.array(hf.get('x_test_with_past'))
    y_test_with_past = np.array(hf.get('y_test_with_past'))  

In [51]:
with h5py.File('crf.features.hdf5','r') as crff:
    # T x C' x C matrix where:
    # T = Number of time steps in the sequence
    # C' = Label of previous step
    # C = Label of current step
    # Note that C' = C = 6
    scores_train = np.array(crff.get('scores_train'))
    scores_test = np.array(crff.get('scores_test'))

In [53]:
scores_train.shape

(7351L, 6L, 6L)

In [48]:
scores_test.shape

(2946L, 6L, 6L)

In [3]:
s_train

array([ 1,  1,  1, ..., 30, 30, 30], dtype=int64)

In [50]:
x_test.shape

(2947L, 561L)

In [4]:
x_train.shape

(7352L, 561L)

In [5]:
y_train.shape

(7352L,)

In [6]:
# convert data into a list of sequences of length T
def convert(T, slice_features = False):
    if slice_features:
        x_trn = np.concatenate((x_train[:, :3], x_train[:, 41:44]), axis=1)
        x_tst = np.concatenate((x_test [:, :3], x_test [:, 41:44]), axis=1)
    else:
        x_trn = x_train
        x_tst = x_test
        
    X_train_list = [x_trn  [i*T:(i+1)*T,:] for i in range(x_trn.shape  [0] / T + 1)]
    Y_train_list = [y_train[i*T:(i+1)*T]-1 for i in range(y_train.shape[0] / T + 1)]

    X_test_list = [x_tst [i*T:(i+1)*T,:] for i in range(x_tst.shape [0] / T + 1)]
    Y_test_list = [y_test[i*T:(i+1)*T]-1 for i in range(y_test.shape[0] / T + 1)]

    print 'X_train_list = {} sequences of size {}'.format(len(X_train_list), X_train_list[0].shape)
    print 'Y_train_list = {} sequences of size {}'.format(len(Y_train_list), Y_train_list[0].shape)
    print 'X_test_list  = {} sequences of size {}'.format(len(X_test_list) , X_test_list[0].shape)
    print 'Y_test_list  = {} sequences of size {}'.format(len(Y_test_list) , Y_test_list[0].shape)
    
    return X_train_list, Y_train_list, X_test_list, Y_test_list

In [61]:
class CRF:
    def __init__(self,C,D,sigma=10):
        self.v = sigma ** 2
        self.v2 = self.v * 2
        self.C = C # number of classes
        self.D = D # number of features
        self.theta  = np.random.randn(1)

    def get_features(self, x, ind, training = True):
        """
        x: 2D feature array of size T x D
        ind: Index of this sequence in the list
        return: 4D array of size T x C x C x D' where dimension:
                0 = T or time or sequence index
                1 = y' or previous label
                2 = y  or current  label
                3 = f(y',y,x,i) for each feature i
        """
        result = np.zeros((len(x), self.C, self.C, 1))
        score_offset = ind * x.shape[0] - 1
        if training:
            scores = scores_train
        else:
            scores = scores_test
        for i in range(len(x)):
            current_features = x[i]
            for j in range(self.C):
                for k in range(self.C):
                    if i == 0 and ind == 0:
                        # first time step so no previous information
                        result[i,j,k] = 0
                    else:
                        result[i,j,k] = scores[score_offset + i, j, k]
#                     result[i,j,k, 2 :] = current_features # main features
#                     result[i,j,k, 0] = j # features for previous label
#                     result[i,j,k, 1] = k # features for current label
        return result
    
    def get_features_labels(self, X_list, Y_list):
        observations = [ self.get_features(X_list[i], i) for i in range(len(X_list)) ]
        labels = len(Y_list) * [None]
        for i in range(len(Y_list)):
            # start from end of previous sequence
            start = Y_list[i-1][-1] if i > 0 else Y_list[i][0]
            end = Y_list[i+1][0] if i < len(Y_list) - 1 else Y_list[i][-1]
            labels[i] = np.array([start] + list(Y_list[i]) + [end])
        return (observations, labels)
        
    def regulariser(self,w):
        return np.sum(w ** 2) /self.v2

    def regulariser_deriv(self,w):
        return np.sum(w) / self.v

    def log_dot_vm(self, loga, logM):
        '''
        Add loga to each column of logM then perform logsumexp.
        loga: 1D array of size C
        logM: 2D array of size C x C
        '''
        return misc.logsumexp(loga.reshape(loga.shape + (1,)) + logM, axis=0)
    
    def log_dot_mv(self, logM, logb):
        '''
        Add logb to each row of logM then perform logsumexp.
        logM: 2D array of size C x C
        logb: 1D array of size C
        '''
        return misc.logsumexp(logM + logb.reshape((1,) + logb.shape), axis=1)

    def forward(self, M, start=0):
        '''
        M: 3D matrix of size (T + 1) x C x C
        '''
        alphas = np.NINF * np.ones((M.shape[0],M.shape[1])) # (T + 1) x C
#         alphas = np.zeros((M.shape[0],M.shape[1])) # (T + 1) x C
        alpha  = alphas[0] # 1 x C
        alpha[start] = 0
        for i in range(M.shape[0]-1):
            alpha = alphas[i+1] = self.log_dot_vm(alpha, M[i])
        alpha = self.log_dot_vm(alpha,M[-1])
        return (alphas,alpha)

    def backward(self, M, end=-1):
        betas = np.zeros((M.shape[0],M.shape[1])) # (T + 1) x C
#         betas = np.NINF * np.ones((M.shape[0],M.shape[1])) # (T + 1) x C
        beta  = betas[-1]
        beta[end] = 0
        for i in reversed(range(M.shape[0]-1)):
            beta = betas[i] = self.log_dot_mv(M[i+1], beta)
        beta = self.log_dot_mv(M[0],beta)
        return (betas,beta)

    def neg_likelihood_and_deriv(self, x_vec_list, y_vec_list, theta, debug=False):
        likelihood = 0
        derivative = np.zeros(len(self.theta))
        for x_vec,y_vec in zip(x_vec_list,y_vec_list):
            """
            features:       (T + 1) x C x C x D'
            M:              (T + 1) x C x C
            alphas:         (T + 1) x C
            betas:          (T + 1) x C
            log_probs:      (T + 1) x C x C 
            `unnormalised` value here is alpha * M * beta, an unnormalised probability
            """
            features        = x_vec
            length          = x_vec.shape[0]
            yp_vec_ids      = y_vec[:-2]
            y_vec_ids       = y_vec[2:]
            log_M           = np.dot(features,theta) # (T + 1) x C x C 
            log_alphas,last = self.forward(log_M, y_vec[0])
            log_betas, zero = self.backward(log_M, y_vec[-1])
            time,state      = log_alphas.shape

            # reshape
            log_alphas1 = log_alphas.reshape(time,state,1)
            log_betas1  = log_betas.reshape(time,1,state)
            log_Z       = misc.logsumexp(last) # partition function
            log_probs   = log_alphas1 + log_M + log_betas1 - log_Z # P(y',y|x)
            #                 TxCx1     TxCxC      Tx1xC      1
            log_probs   = log_probs.reshape(log_probs.shape+(1,)) # T x C x C x 1
            
            if debug:
                print '**********'
                print 'length'
                print length
                print 'time'
                print time
                print 'state'
                print state
                print 'log_M.shape'
                print log_M.shape
                print 'log_Z'
                print log_Z
                print 'len(yp_vec_ids)'
                print len(yp_vec_ids)
                print 'len(y_vec_ids)'
                print len(y_vec_ids)
                print 'features.shape'
                print features.shape
                print 'yp_vec_ids'
                print yp_vec_ids
                print 'y_vec_ids'
                print y_vec_ids
                print 'log_probs.shape'
                print log_probs.shape
                print '**********'

            """
            log_probs:    T x C x C x 1
            features:     T x C x C x D'
            exp_features: D'
            emp_features: D'
            yp_vec_ids  : T
            y_vec_ids   : T
            """
            # Compute expected value of feature functions under empirical distribution
            exp_features = np.sum( np.exp(log_probs) * features, axis = (0,1,2) )
            # Compute expected value of feature functions under model distribution
            emp_features = np.sum( features[ range(length), yp_vec_ids, y_vec_ids ], axis = 0 )
            
            if debug:
                print 'exp_features.shape'
                print exp_features.shape
                print 'emp_features.shape'
                print emp_features.shape
                sys.exit(0)

            likelihood += np.sum(log_M[ range(length), yp_vec_ids, y_vec_ids ]) - log_Z
            derivative += emp_features - exp_features
        
        print 'likelihood = {}'.format(likelihood - self.regulariser(theta))
        return (
            - ( likelihood - self.regulariser(theta)), 
            - ( derivative - self.regulariser_deriv(theta))
        )
    
    def predict(self, x_vec, ind, debug=False):
        # small overhead, no copying is done
        """
        features:       len(x_vec+1) x Y' x Y x K
        log_potential:  len(x_vec+1) x Y' x Y
        argmaxes:       len(x_vec+1) x Y'
        """
        features  = self.get_features(x_vec, ind, training = False)
        log_potential = np.dot(features,self.theta)
        return self.viterbi_bp(log_potential,len(x_vec),self.C)
    
    def viterbi_bp(self,log_potential,N,K,debug=False):
        g0 = log_potential[0,0]
        g  = log_potential[1:]

        B = np.ones((N,K), dtype=np.int32) * -1
        # compute max-marginals and backtrace matrix
        V = g0
        for t in xrange(1,N):
            U = np.empty(K)
            for y in xrange(K):
                w = V + g[t-1,:,y]
                B[t,y] = b = w.argmax()
                U[y] = w[b]
            V = U
        # extract the best path by brack-tracking
        y = V.argmax()
        trace = []
        for t in reversed(xrange(N)):
            trace.append(y)
            y = B[t, y]
        trace.reverse()
        return trace

    def train(self,x_seq,y_seq,debug=False):
        '''
        x_seq: List of 2D feature array of size T x D
        y_seq: List of 1D label array of size T
        '''
        X,Y = self.get_features_labels(x_seq,y_seq)
        l = lambda theta: self.neg_likelihood_and_deriv(X,Y,theta,debug)
        val = optimize.fmin_l_bfgs_b(l,self.theta)
        if debug: print val
        self.theta,_,_  = val
        return self.theta

In [62]:
T = 100 # number of time steps in each sequence
X_train_list, Y_train_list, X_test_list, Y_test_list = convert(T, slice_features=True)

C = 6 # number of classes
D = X_train_list[0].shape[1] # number of features
print 'C = {}, D = {}'.format(C,D)
crf = CRF(C,D)
crf.train(X_train_list, Y_train_list, debug=False)

total_correct = 0
total_count = 0
Y_hat_list = []
for i in range(len(X_test_list)):
    Y_hat = crf.predict(X_test_list[i], i)
    total_correct += np.sum(Y_hat == Y_test_list[i])
    total_count += len(Y_test_list[i])
    Y_hat_list.append(Y_hat)
print 'accuracy = {}'.format(float(total_correct) / total_count)

X_train_list = 74 sequences of size (100L, 6L)
Y_train_list = 74 sequences of size (100L,)
X_test_list  = 30 sequences of size (100L, 6L)
Y_test_list  = 30 sequences of size (100L,)
C = 6, D = 6
likelihood = -8572.87584207
likelihood = -2968.88758009
likelihood = -2851.71819384
likelihood = -2476.82378582
likelihood = -2769.06521974
likelihood = -2397.25435826
likelihood = -2396.22165014
likelihood = -2396.0502815
likelihood = -2396.0500419
likelihood = -2396.05004186
accuracy = 0.953512046149


In [44]:
correct = 0
for t in range(len(X_test_list)):
    for i in range(X_test_list[t].shape[0]):
        d = X_test_list[t][i].reshape((1,) + X_test_list[t][i].shape) - X_train_list[t]
        nl = np.argmin(np.sum(d*d))
        if Y_test_list[t][i] == Y_train_list[t][nl]:
            correct += 1
print correct
print x_test.shape[0]
print float(correct) / num_tests

536
2947
5.36


In [34]:
o,l = crf.get_features_labels(X_train_list, Y_train_list)
yprev = Y_train_list[0][:3]
ycurr = Y_train_list[0][1:4]
print yprev
print ycurr
print o[0].shape
oo = o[0][ range(3), yprev, ycurr ]
print oo
print '------'
print np.sum(oo, axis = 0)

[4 4 4]
[4 4 4]
(100L, 6L, 6L, 18L)
[[ 0.          0.          0.          0.          1.          0.          0.
   0.          0.          0.          1.          0.          0.28858451
  -0.02029417 -0.13290514 -0.14083968  0.11537494 -0.98524969]
 [ 0.          0.          0.          0.          1.          0.          0.
   0.          0.          0.          1.          0.          0.27841883
  -0.01641057 -0.12352019 -0.14155127  0.10937881 -0.99741134]
 [ 0.          0.          0.          0.          1.          0.          0.
   0.          0.          0.          1.          0.          0.27965306
  -0.01946716 -0.11346169 -0.14200984  0.10188392 -0.99957395]]
------
[ 0.          0.          0.          0.          3.          0.          0.
  0.          0.          0.          3.          0.          0.8466564
 -0.05617189 -0.36988702 -0.42440079  0.32663767 -2.98223498]


In [171]:
np.array(Y_hat_list[4]).T

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [129]:
X,Y = crf.get_features_labels(X_train_list,Y_train_list)
mm = np.dot(X[0], crf.theta)
log_alphas,last = crf.forward(mm)

In [136]:
crf.theta

array([-6.24268359,  1.20707888,  1.06844954,  1.33170123,  1.57438902,
        1.4241703 ,  5.92117355, -1.59983502, -1.54587767, -1.54050549,
       -1.71867424, -1.544992  , -0.15878944,  0.11982213, -1.17793511,
        1.74592755,  0.46401028, -0.54626748])

In [119]:
X[0].shape

(100L, 6L, 6L, 18L)

In [124]:
Y[0].shape

(101L,)

In [125]:
mm.shape

(100L, 6L, 6L)

In [130]:
log_alphas.shape

(100L, 6L)

In [153]:
x = np.arange(1,6)
print x.reshape(x.shape + (1,)) + np.ones((5,5))
print x.reshape((1,) + x.shape) + np.ones((5,5))
print misc.logsumexp(np.ones((6,6)))

[[ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.]]
[[ 2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.]]
4.58351893846


In [156]:
np.log(np.exp(1) * 36)

4.5835189384561099